/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_FACTORY_COMMAND_FACTORY_COMMAND_PB_H_INCLUDED
#define PB_FACTORY_COMMAND_FACTORY_COMMAND_PB_H_INCLUDED
#include <pb.h>
#include "factory_data.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _factory_command_FactoryReadRequest {
    pb_callback_t items;
} factory_command_FactoryReadRequest;

typedef struct _factory_command_FactoryReadResponse {
    bool has_data;
    factory_data_FactoryData data;
} factory_command_FactoryReadResponse;

typedef struct _factory_command_FactoryWriteRequest {
    bool has_data;
    factory_data_FactoryData data;
} factory_command_FactoryWriteRequest;

typedef struct _factory_command_FactoryWriteResponse {
    pb_callback_t items;
} factory_command_FactoryWriteResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define factory_command_FactoryReadRequest_init_default {{{NULL}, NULL}}
#define factory_command_FactoryReadResponse_init_default {false, factory_data_FactoryData_init_default}
#define factory_command_FactoryWriteRequest_init_default {false, factory_data_FactoryData_init_default}
#define factory_command_FactoryWriteResponse_init_default {{{NULL}, NULL}}
#define factory_command_FactoryReadRequest_init_zero {{{NULL}, NULL}}
#define factory_command_FactoryReadResponse_init_zero {false, factory_data_FactoryData_init_zero}
#define factory_command_FactoryWriteRequest_init_zero {false, factory_data_FactoryData_init_zero}
#define factory_command_FactoryWriteResponse_init_zero {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define factory_command_FactoryReadRequest_items_tag 1
#define factory_command_FactoryReadResponse_data_tag 1
#define factory_command_FactoryWriteRequest_data_tag 1
#define factory_command_FactoryWriteResponse_items_tag 1

/* Struct field encoding specification for nanopb */
#define factory_command_FactoryReadRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UENUM,    items,             1)
#define factory_command_FactoryReadRequest_CALLBACK pb_default_field_callback
#define factory_command_FactoryReadRequest_DEFAULT NULL

#define factory_command_FactoryReadResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              1)
#define factory_command_FactoryReadResponse_CALLBACK NULL
#define factory_command_FactoryReadResponse_DEFAULT NULL
#define factory_command_FactoryReadResponse_data_MSGTYPE factory_data_FactoryData

#define factory_command_FactoryWriteRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              1)
#define factory_command_FactoryWriteRequest_CALLBACK NULL
#define factory_command_FactoryWriteRequest_DEFAULT NULL
#define factory_command_FactoryWriteRequest_data_MSGTYPE factory_data_FactoryData

#define factory_command_FactoryWriteResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UENUM,    items,             1)
#define factory_command_FactoryWriteResponse_CALLBACK pb_default_field_callback
#define factory_command_FactoryWriteResponse_DEFAULT NULL

extern const pb_msgdesc_t factory_command_FactoryReadRequest_msg;
extern const pb_msgdesc_t factory_command_FactoryReadResponse_msg;
extern const pb_msgdesc_t factory_command_FactoryWriteRequest_msg;
extern const pb_msgdesc_t factory_command_FactoryWriteResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define factory_command_FactoryReadRequest_fields &factory_command_FactoryReadRequest_msg
#define factory_command_FactoryReadResponse_fields &factory_command_FactoryReadResponse_msg
#define factory_command_FactoryWriteRequest_fields &factory_command_FactoryWriteRequest_msg
#define factory_command_FactoryWriteResponse_fields &factory_command_FactoryWriteResponse_msg

/* Maximum encoded size of messages (where known) */
/* factory_command_FactoryReadRequest_size depends on runtime parameters */
/* factory_command_FactoryWriteResponse_size depends on runtime parameters */
#if defined(factory_data_FactoryData_size)
#define FACTORY_COMMAND_FACTORY_COMMAND_PB_H_MAX_SIZE factory_command_FactoryReadResponse_size
#define factory_command_FactoryReadResponse_size (6 + factory_data_FactoryData_size)
#define factory_command_FactoryWriteRequest_size (6 + factory_data_FactoryData_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
