/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "factory_transaction.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(factory_transaction_FactoryRequest, factory_transaction_FactoryRequest, 2)


PB_BIND(factory_transaction_FactoryResponse, factory_transaction_FactoryResponse, 2)





