/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_FACTORY_TRANSACTION_FACTORY_TRANSACTION_PB_H_INCLUDED
#define PB_FACTORY_TRANSACTION_FACTORY_TRANSACTION_PB_H_INCLUDED
#include <pb.h>
#include "factory_command.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _factory_transaction_FactoryStatusCode {
    factory_transaction_FactoryStatusCode_FACTORY_STATUS_CODE_UNSPECIFIED = 0,
    factory_transaction_FactoryStatusCode_FACTORY_STATUS_CODE_OK = 1,
    factory_transaction_FactoryStatusCode_FACTORY_STATUS_CODE_INVALID_TRANSACTION = 2,
    factory_transaction_FactoryStatusCode_FACTORY_STATUS_CODE_INVALID_ARGUMENT = 3,
    factory_transaction_FactoryStatusCode_FACTORY_STATUS_CODE_INVALID_ITEM = 4,
    factory_transaction_FactoryStatusCode_FACTORY_STATUS_CODE_INVALID_DATA = 5,
    factory_transaction_FactoryStatusCode_FACTORY_STATUS_CODE_INTERNAL_ERROR = 6,
    factory_transaction_FactoryStatusCode_FACTORY_STATUS_CODE_UNSUPPORTED = 7
} factory_transaction_FactoryStatusCode;

/* Struct definitions */
typedef struct _factory_transaction_FactoryRequest {
    uint32_t transaction_id;
    pb_size_t which_transaction;
    union _factory_transaction_FactoryRequest_transaction {
        factory_command_FactoryReadRequest read;
        factory_command_FactoryWriteRequest write;
    } transaction;
} factory_transaction_FactoryRequest;

typedef struct _factory_transaction_FactoryResponse {
    uint32_t transaction_id;
    factory_transaction_FactoryStatusCode status;
    pb_size_t which_transaction;
    union _factory_transaction_FactoryResponse_transaction {
        factory_command_FactoryReadResponse read;
        factory_command_FactoryWriteResponse write;
    } transaction;
} factory_transaction_FactoryResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _factory_transaction_FactoryStatusCode_MIN factory_transaction_FactoryStatusCode_FACTORY_STATUS_CODE_UNSPECIFIED
#define _factory_transaction_FactoryStatusCode_MAX factory_transaction_FactoryStatusCode_FACTORY_STATUS_CODE_UNSUPPORTED
#define _factory_transaction_FactoryStatusCode_ARRAYSIZE ((factory_transaction_FactoryStatusCode)(factory_transaction_FactoryStatusCode_FACTORY_STATUS_CODE_UNSUPPORTED+1))


#define factory_transaction_FactoryResponse_status_ENUMTYPE factory_transaction_FactoryStatusCode


/* Initializer values for message structs */
#define factory_transaction_FactoryRequest_init_default {0, 0, {factory_command_FactoryReadRequest_init_default}}
#define factory_transaction_FactoryResponse_init_default {0, _factory_transaction_FactoryStatusCode_MIN, 0, {factory_command_FactoryReadResponse_init_default}}
#define factory_transaction_FactoryRequest_init_zero {0, 0, {factory_command_FactoryReadRequest_init_zero}}
#define factory_transaction_FactoryResponse_init_zero {0, _factory_transaction_FactoryStatusCode_MIN, 0, {factory_command_FactoryReadResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define factory_transaction_FactoryRequest_transaction_id_tag 1
#define factory_transaction_FactoryRequest_read_tag 100
#define factory_transaction_FactoryRequest_write_tag 101
#define factory_transaction_FactoryResponse_transaction_id_tag 1
#define factory_transaction_FactoryResponse_status_tag 2
#define factory_transaction_FactoryResponse_read_tag 100
#define factory_transaction_FactoryResponse_write_tag 101

/* Struct field encoding specification for nanopb */
#define factory_transaction_FactoryRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   transaction_id,    1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (transaction,read,transaction.read), 100) \
X(a, STATIC,   ONEOF,    MESSAGE,  (transaction,write,transaction.write), 101)
#define factory_transaction_FactoryRequest_CALLBACK NULL
#define factory_transaction_FactoryRequest_DEFAULT NULL
#define factory_transaction_FactoryRequest_transaction_read_MSGTYPE factory_command_FactoryReadRequest
#define factory_transaction_FactoryRequest_transaction_write_MSGTYPE factory_command_FactoryWriteRequest

#define factory_transaction_FactoryResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   transaction_id,    1) \
X(a, STATIC,   SINGULAR, UENUM,    status,            2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (transaction,read,transaction.read), 100) \
X(a, STATIC,   ONEOF,    MESSAGE,  (transaction,write,transaction.write), 101)
#define factory_transaction_FactoryResponse_CALLBACK NULL
#define factory_transaction_FactoryResponse_DEFAULT NULL
#define factory_transaction_FactoryResponse_transaction_read_MSGTYPE factory_command_FactoryReadResponse
#define factory_transaction_FactoryResponse_transaction_write_MSGTYPE factory_command_FactoryWriteResponse

extern const pb_msgdesc_t factory_transaction_FactoryRequest_msg;
extern const pb_msgdesc_t factory_transaction_FactoryResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define factory_transaction_FactoryRequest_fields &factory_transaction_FactoryRequest_msg
#define factory_transaction_FactoryResponse_fields &factory_transaction_FactoryResponse_msg

/* Maximum encoded size of messages (where known) */
#if defined(factory_command_FactoryReadRequest_size) && defined(factory_command_FactoryWriteRequest_size)
union factory_transaction_FactoryRequest_transaction_size_union {char f100[(7 + factory_command_FactoryReadRequest_size)]; char f101[(7 + factory_command_FactoryWriteRequest_size)];};
#endif
#if defined(factory_command_FactoryReadResponse_size) && defined(factory_command_FactoryWriteResponse_size)
union factory_transaction_FactoryResponse_transaction_size_union {char f100[(7 + factory_command_FactoryReadResponse_size)]; char f101[(7 + factory_command_FactoryWriteResponse_size)];};
#endif
#if defined(factory_command_FactoryReadRequest_size) && defined(factory_command_FactoryWriteRequest_size)
#define factory_transaction_FactoryRequest_size  (6 + sizeof(union factory_transaction_FactoryRequest_transaction_size_union))
#endif
#if defined(factory_command_FactoryReadResponse_size) && defined(factory_command_FactoryWriteResponse_size)
#define FACTORY_TRANSACTION_FACTORY_TRANSACTION_PB_H_MAX_SIZE factory_transaction_FactoryResponse_size
#define factory_transaction_FactoryResponse_size (8 + sizeof(union factory_transaction_FactoryResponse_transaction_size_union))
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
