/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_FACTORY_DATA_FACTORY_DATA_PB_H_INCLUDED
#define PB_FACTORY_DATA_FACTORY_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _factory_data_FactoryDataItem {
    factory_data_FactoryDataItem_FACTORY_DATA_ITEM_UNSPECIFIED = 0,
    factory_data_FactoryDataItem_FACTORY_DATA_ITEM_SERIAL_NUMBER = 1,
    factory_data_FactoryDataItem_FACTORY_DATA_ITEM_MANUFACTURED_DATE = 2,
    factory_data_FactoryDataItem_FACTORY_DATA_ITEM_VENDOR_ID = 101,
    factory_data_FactoryDataItem_FACTORY_DATA_ITEM_PRODUCT_ID = 102,
    factory_data_FactoryDataItem_FACTORY_DATA_ITEM_DAC_CERT = 201,
    factory_data_FactoryDataItem_FACTORY_DATA_ITEM_DAC_PUBLIC_KEY = 202,
    factory_data_FactoryDataItem_FACTORY_DATA_ITEM_DAC_PRIVATE_KEY = 203,
    factory_data_FactoryDataItem_FACTORY_DATA_ITEM_PAI_CERT = 204,
    factory_data_FactoryDataItem_FACTORY_DATA_ITEM_CERTIFICATION_DECLARATION = 205,
    factory_data_FactoryDataItem_FACTORY_DATA_ITEM_ONBOARDING_PAYLOAD = 301,
    factory_data_FactoryDataItem_FACTORY_DATA_ITEM_SPAKE2P_PASSCODE = 302,
    factory_data_FactoryDataItem_FACTORY_DATA_ITEM_SPAKE2P_SALT = 303,
    factory_data_FactoryDataItem_FACTORY_DATA_ITEM_SPAKE2P_ITERATION_COUNT = 304,
    factory_data_FactoryDataItem_FACTORY_DATA_ITEM_SPAKE2P_VERIFIER = 305
} factory_data_FactoryDataItem;

/* Struct definitions */
typedef struct _factory_data_FactoryData {
    pb_callback_t serial_number;
    pb_callback_t manufactured_date;
    bool has_vendor_id;
    uint32_t vendor_id;
    bool has_product_id;
    uint32_t product_id;
    pb_callback_t dac_cert;
    pb_callback_t dac_public_key;
    pb_callback_t dac_private_key;
    pb_callback_t pai_cert;
    pb_callback_t certification_declaration;
    pb_callback_t onboarding_payload;
    bool has_spake2p_passcode;
    uint32_t spake2p_passcode;
    pb_callback_t spake2p_salt;
    bool has_spake2p_iteration_count;
    uint32_t spake2p_iteration_count;
    pb_callback_t spake2p_verifier;
} factory_data_FactoryData;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _factory_data_FactoryDataItem_MIN factory_data_FactoryDataItem_FACTORY_DATA_ITEM_UNSPECIFIED
#define _factory_data_FactoryDataItem_MAX factory_data_FactoryDataItem_FACTORY_DATA_ITEM_SPAKE2P_VERIFIER
#define _factory_data_FactoryDataItem_ARRAYSIZE ((factory_data_FactoryDataItem)(factory_data_FactoryDataItem_FACTORY_DATA_ITEM_SPAKE2P_VERIFIER+1))



/* Initializer values for message structs */
#define factory_data_FactoryData_init_default    {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define factory_data_FactoryData_init_zero       {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define factory_data_FactoryData_serial_number_tag 1
#define factory_data_FactoryData_manufactured_date_tag 2
#define factory_data_FactoryData_vendor_id_tag   101
#define factory_data_FactoryData_product_id_tag  102
#define factory_data_FactoryData_dac_cert_tag    201
#define factory_data_FactoryData_dac_public_key_tag 202
#define factory_data_FactoryData_dac_private_key_tag 203
#define factory_data_FactoryData_pai_cert_tag    204
#define factory_data_FactoryData_certification_declaration_tag 205
#define factory_data_FactoryData_onboarding_payload_tag 301
#define factory_data_FactoryData_spake2p_passcode_tag 302
#define factory_data_FactoryData_spake2p_salt_tag 303
#define factory_data_FactoryData_spake2p_iteration_count_tag 304
#define factory_data_FactoryData_spake2p_verifier_tag 305

/* Struct field encoding specification for nanopb */
#define factory_data_FactoryData_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   serial_number,     1) \
X(a, CALLBACK, OPTIONAL, STRING,   manufactured_date,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   vendor_id,       101) \
X(a, STATIC,   OPTIONAL, UINT32,   product_id,      102) \
X(a, CALLBACK, OPTIONAL, BYTES,    dac_cert,        201) \
X(a, CALLBACK, OPTIONAL, BYTES,    dac_public_key,  202) \
X(a, CALLBACK, OPTIONAL, BYTES,    dac_private_key, 203) \
X(a, CALLBACK, OPTIONAL, BYTES,    pai_cert,        204) \
X(a, CALLBACK, OPTIONAL, BYTES,    certification_declaration, 205) \
X(a, CALLBACK, OPTIONAL, BYTES,    onboarding_payload, 301) \
X(a, STATIC,   OPTIONAL, UINT32,   spake2p_passcode, 302) \
X(a, CALLBACK, OPTIONAL, BYTES,    spake2p_salt,    303) \
X(a, STATIC,   OPTIONAL, UINT32,   spake2p_iteration_count, 304) \
X(a, CALLBACK, OPTIONAL, BYTES,    spake2p_verifier, 305)
#define factory_data_FactoryData_CALLBACK pb_default_field_callback
#define factory_data_FactoryData_DEFAULT NULL

extern const pb_msgdesc_t factory_data_FactoryData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define factory_data_FactoryData_fields &factory_data_FactoryData_msg

/* Maximum encoded size of messages (where known) */
/* factory_data_FactoryData_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
