/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "factory_command.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(factory_command_FactoryReadRequest, factory_command_FactoryReadRequest, AUTO)


PB_BIND(factory_command_FactoryReadResponse, factory_command_FactoryReadResponse, 2)


PB_BIND(factory_command_FactoryWriteRequest, factory_command_FactoryWriteRequest, 2)


PB_BIND(factory_command_FactoryWriteResponse, factory_command_FactoryWriteResponse, AUTO)



