# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: factory_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'factory_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66\x61\x63tory_data.proto\x12\x07\x66\x61\x63tory\"\xb7\x04\n\x0b\x46\x61\x63toryData\x12+\n\x06system\x18\x01 \x01(\x0b\x32\x1b.factory.FactoryData.System\x12+\n\x06matter\x18\x02 \x01(\x0b\x32\x1b.factory.FactoryData.Matter\x1a;\n\x06System\x12\x15\n\rserial_number\x18\x01 \x01(\t\x12\x1a\n\x12manufacturing_date\x18\x02 \x01(\t\x1a\x90\x03\n\x06Matter\x12<\n\x0b\x61ttestation\x18\x01 \x01(\x0b\x32\'.factory.FactoryData.Matter.Attestation\x12@\n\rcommissioning\x18\x02 \x01(\x0b\x32).factory.FactoryData.Matter.Commissioning\x1am\n\x0b\x41ttestation\x12\x10\n\x08\x64\x61\x63_cert\x18\x01 \x01(\x0c\x12\x17\n\x0f\x64\x61\x63_private_key\x18\x02 \x01(\x0c\x12\x10\n\x08pai_cert\x18\x03 \x01(\x0c\x12!\n\x19\x63\x65rtification_declaration\x18\x04 \x01(\x0c\x1a\x96\x01\n\rCommissioning\x12\x18\n\x10spake2p_passcode\x18\x01 \x01(\r\x12\x14\n\x0cspake2p_salt\x18\x02 \x01(\x0c\x12\x1f\n\x17spake2p_iteration_count\x18\x03 \x01(\r\x12\x18\n\x10spake2p_verifier\x18\x04 \x01(\x0c\x12\x1a\n\x12onboarding_payload\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'factory_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACTORYDATA']._serialized_start=32
  _globals['_FACTORYDATA']._serialized_end=599
  _globals['_FACTORYDATA_SYSTEM']._serialized_start=137
  _globals['_FACTORYDATA_SYSTEM']._serialized_end=196
  _globals['_FACTORYDATA_MATTER']._serialized_start=199
  _globals['_FACTORYDATA_MATTER']._serialized_end=599
  _globals['_FACTORYDATA_MATTER_ATTESTATION']._serialized_start=337
  _globals['_FACTORYDATA_MATTER_ATTESTATION']._serialized_end=446
  _globals['_FACTORYDATA_MATTER_COMMISSIONING']._serialized_start=449
  _globals['_FACTORYDATA_MATTER_COMMISSIONING']._serialized_end=599
# @@protoc_insertion_point(module_scope)
