# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: factory_transaction.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import factory_command_pb2 as factory__command__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='factory_transaction.proto',
  package='factory.transaction',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x66\x61\x63tory_transaction.proto\x12\x13\x66\x61\x63tory.transaction\x1a\x15\x66\x61\x63tory_command.proto\"\xa3\x01\n\x0e\x46\x61\x63toryRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\r\x12\x33\n\x04read\x18\x64 \x01(\x0b\x32#.factory.command.FactoryReadRequestH\x00\x12\x35\n\x05write\x18\x65 \x01(\x0b\x32$.factory.command.FactoryWriteRequestH\x00\x42\r\n\x0btransaction\"\xde\x01\n\x0f\x46\x61\x63toryResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\r\x12\x36\n\x06status\x18\x02 \x01(\x0e\x32&.factory.transaction.FactoryStatusCode\x12\x34\n\x04read\x18\x64 \x01(\x0b\x32$.factory.command.FactoryReadResponseH\x00\x12\x36\n\x05write\x18\x65 \x01(\x0b\x32%.factory.command.FactoryWriteResponseH\x00\x42\r\n\x0btransaction*\xc4\x02\n\x11\x46\x61\x63toryStatusCode\x12#\n\x1f\x46\x41\x43TORY_STATUS_CODE_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x46\x41\x43TORY_STATUS_CODE_OK\x10\x01\x12+\n\'FACTORY_STATUS_CODE_INVALID_TRANSACTION\x10\x02\x12(\n$FACTORY_STATUS_CODE_INVALID_ARGUMENT\x10\x03\x12$\n FACTORY_STATUS_CODE_INVALID_ITEM\x10\x04\x12$\n FACTORY_STATUS_CODE_INVALID_DATA\x10\x05\x12&\n\"FACTORY_STATUS_CODE_INTERNAL_ERROR\x10\x06\x12#\n\x1f\x46\x41\x43TORY_STATUS_CODE_UNSUPPORTED\x10\x07\x62\x06proto3'
  ,
  dependencies=[factory__command__pb2.DESCRIPTOR,])

_FACTORYSTATUSCODE = _descriptor.EnumDescriptor(
  name='FactoryStatusCode',
  full_name='factory.transaction.FactoryStatusCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FACTORY_STATUS_CODE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FACTORY_STATUS_CODE_OK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FACTORY_STATUS_CODE_INVALID_TRANSACTION', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FACTORY_STATUS_CODE_INVALID_ARGUMENT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FACTORY_STATUS_CODE_INVALID_ITEM', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FACTORY_STATUS_CODE_INVALID_DATA', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FACTORY_STATUS_CODE_INTERNAL_ERROR', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FACTORY_STATUS_CODE_UNSUPPORTED', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=465,
  serialized_end=789,
)
_sym_db.RegisterEnumDescriptor(_FACTORYSTATUSCODE)

FactoryStatusCode = enum_type_wrapper.EnumTypeWrapper(_FACTORYSTATUSCODE)
FACTORY_STATUS_CODE_UNSPECIFIED = 0
FACTORY_STATUS_CODE_OK = 1
FACTORY_STATUS_CODE_INVALID_TRANSACTION = 2
FACTORY_STATUS_CODE_INVALID_ARGUMENT = 3
FACTORY_STATUS_CODE_INVALID_ITEM = 4
FACTORY_STATUS_CODE_INVALID_DATA = 5
FACTORY_STATUS_CODE_INTERNAL_ERROR = 6
FACTORY_STATUS_CODE_UNSUPPORTED = 7



_FACTORYREQUEST = _descriptor.Descriptor(
  name='FactoryRequest',
  full_name='factory.transaction.FactoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='factory.transaction.FactoryRequest.transaction_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='read', full_name='factory.transaction.FactoryRequest.read', index=1,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='write', full_name='factory.transaction.FactoryRequest.write', index=2,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='transaction', full_name='factory.transaction.FactoryRequest.transaction',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=74,
  serialized_end=237,
)


_FACTORYRESPONSE = _descriptor.Descriptor(
  name='FactoryResponse',
  full_name='factory.transaction.FactoryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='factory.transaction.FactoryResponse.transaction_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='factory.transaction.FactoryResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='read', full_name='factory.transaction.FactoryResponse.read', index=2,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='write', full_name='factory.transaction.FactoryResponse.write', index=3,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='transaction', full_name='factory.transaction.FactoryResponse.transaction',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=240,
  serialized_end=462,
)

_FACTORYREQUEST.fields_by_name['read'].message_type = factory__command__pb2._FACTORYREADREQUEST
_FACTORYREQUEST.fields_by_name['write'].message_type = factory__command__pb2._FACTORYWRITEREQUEST
_FACTORYREQUEST.oneofs_by_name['transaction'].fields.append(
  _FACTORYREQUEST.fields_by_name['read'])
_FACTORYREQUEST.fields_by_name['read'].containing_oneof = _FACTORYREQUEST.oneofs_by_name['transaction']
_FACTORYREQUEST.oneofs_by_name['transaction'].fields.append(
  _FACTORYREQUEST.fields_by_name['write'])
_FACTORYREQUEST.fields_by_name['write'].containing_oneof = _FACTORYREQUEST.oneofs_by_name['transaction']
_FACTORYRESPONSE.fields_by_name['status'].enum_type = _FACTORYSTATUSCODE
_FACTORYRESPONSE.fields_by_name['read'].message_type = factory__command__pb2._FACTORYREADRESPONSE
_FACTORYRESPONSE.fields_by_name['write'].message_type = factory__command__pb2._FACTORYWRITERESPONSE
_FACTORYRESPONSE.oneofs_by_name['transaction'].fields.append(
  _FACTORYRESPONSE.fields_by_name['read'])
_FACTORYRESPONSE.fields_by_name['read'].containing_oneof = _FACTORYRESPONSE.oneofs_by_name['transaction']
_FACTORYRESPONSE.oneofs_by_name['transaction'].fields.append(
  _FACTORYRESPONSE.fields_by_name['write'])
_FACTORYRESPONSE.fields_by_name['write'].containing_oneof = _FACTORYRESPONSE.oneofs_by_name['transaction']
DESCRIPTOR.message_types_by_name['FactoryRequest'] = _FACTORYREQUEST
DESCRIPTOR.message_types_by_name['FactoryResponse'] = _FACTORYRESPONSE
DESCRIPTOR.enum_types_by_name['FactoryStatusCode'] = _FACTORYSTATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FactoryRequest = _reflection.GeneratedProtocolMessageType('FactoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACTORYREQUEST,
  '__module__' : 'factory_transaction_pb2'
  # @@protoc_insertion_point(class_scope:factory.transaction.FactoryRequest)
  })
_sym_db.RegisterMessage(FactoryRequest)

FactoryResponse = _reflection.GeneratedProtocolMessageType('FactoryResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACTORYRESPONSE,
  '__module__' : 'factory_transaction_pb2'
  # @@protoc_insertion_point(class_scope:factory.transaction.FactoryResponse)
  })
_sym_db.RegisterMessage(FactoryResponse)


# @@protoc_insertion_point(module_scope)
