# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: factory_transaction.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'factory_transaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import factory_command_pb2 as factory__command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66\x61\x63tory_transaction.proto\x12\x13\x66\x61\x63tory.transaction\x1a\x15\x66\x61\x63tory_command.proto\"\xa3\x01\n\x0e\x46\x61\x63toryRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\r\x12\x33\n\x04read\x18\x64 \x01(\x0b\x32#.factory.command.FactoryReadRequestH\x00\x12\x35\n\x05write\x18\x65 \x01(\x0b\x32$.factory.command.FactoryWriteRequestH\x00\x42\r\n\x0btransaction\"\xde\x01\n\x0f\x46\x61\x63toryResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\r\x12\x36\n\x06status\x18\x02 \x01(\x0e\x32&.factory.transaction.FactoryStatusCode\x12\x34\n\x04read\x18\x64 \x01(\x0b\x32$.factory.command.FactoryReadResponseH\x00\x12\x36\n\x05write\x18\x65 \x01(\x0b\x32%.factory.command.FactoryWriteResponseH\x00\x42\r\n\x0btransaction*\xc4\x02\n\x11\x46\x61\x63toryStatusCode\x12#\n\x1f\x46\x41\x43TORY_STATUS_CODE_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x46\x41\x43TORY_STATUS_CODE_OK\x10\x01\x12+\n\'FACTORY_STATUS_CODE_INVALID_TRANSACTION\x10\x02\x12(\n$FACTORY_STATUS_CODE_INVALID_ARGUMENT\x10\x03\x12$\n FACTORY_STATUS_CODE_INVALID_ITEM\x10\x04\x12$\n FACTORY_STATUS_CODE_INVALID_DATA\x10\x05\x12&\n\"FACTORY_STATUS_CODE_INTERNAL_ERROR\x10\x06\x12#\n\x1f\x46\x41\x43TORY_STATUS_CODE_UNSUPPORTED\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'factory_transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACTORYSTATUSCODE']._serialized_start=465
  _globals['_FACTORYSTATUSCODE']._serialized_end=789
  _globals['_FACTORYREQUEST']._serialized_start=74
  _globals['_FACTORYREQUEST']._serialized_end=237
  _globals['_FACTORYRESPONSE']._serialized_start=240
  _globals['_FACTORYRESPONSE']._serialized_end=462
# @@protoc_insertion_point(module_scope)
