# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: factory_command.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import factory_data_pb2 as factory__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='factory_command.proto',
  package='factory.command',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x66\x61\x63tory_command.proto\x12\x0f\x66\x61\x63tory.command\x1a\x12\x66\x61\x63tory_data.proto\"B\n\x12\x46\x61\x63toryReadRequest\x12,\n\x05items\x18\x01 \x03(\x0e\x32\x1d.factory.data.FactoryDataItem\">\n\x13\x46\x61\x63toryReadResponse\x12\'\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x19.factory.data.FactoryData\">\n\x13\x46\x61\x63toryWriteRequest\x12\'\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x19.factory.data.FactoryData\"D\n\x14\x46\x61\x63toryWriteResponse\x12,\n\x05items\x18\x01 \x03(\x0e\x32\x1d.factory.data.FactoryDataItemb\x06proto3'
  ,
  dependencies=[factory__data__pb2.DESCRIPTOR,])




_FACTORYREADREQUEST = _descriptor.Descriptor(
  name='FactoryReadRequest',
  full_name='factory.command.FactoryReadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='factory.command.FactoryReadRequest.items', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=128,
)


_FACTORYREADRESPONSE = _descriptor.Descriptor(
  name='FactoryReadResponse',
  full_name='factory.command.FactoryReadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='factory.command.FactoryReadResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=192,
)


_FACTORYWRITEREQUEST = _descriptor.Descriptor(
  name='FactoryWriteRequest',
  full_name='factory.command.FactoryWriteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='factory.command.FactoryWriteRequest.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=256,
)


_FACTORYWRITERESPONSE = _descriptor.Descriptor(
  name='FactoryWriteResponse',
  full_name='factory.command.FactoryWriteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='factory.command.FactoryWriteResponse.items', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=326,
)

_FACTORYREADREQUEST.fields_by_name['items'].enum_type = factory__data__pb2._FACTORYDATAITEM
_FACTORYREADRESPONSE.fields_by_name['data'].message_type = factory__data__pb2._FACTORYDATA
_FACTORYWRITEREQUEST.fields_by_name['data'].message_type = factory__data__pb2._FACTORYDATA
_FACTORYWRITERESPONSE.fields_by_name['items'].enum_type = factory__data__pb2._FACTORYDATAITEM
DESCRIPTOR.message_types_by_name['FactoryReadRequest'] = _FACTORYREADREQUEST
DESCRIPTOR.message_types_by_name['FactoryReadResponse'] = _FACTORYREADRESPONSE
DESCRIPTOR.message_types_by_name['FactoryWriteRequest'] = _FACTORYWRITEREQUEST
DESCRIPTOR.message_types_by_name['FactoryWriteResponse'] = _FACTORYWRITERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FactoryReadRequest = _reflection.GeneratedProtocolMessageType('FactoryReadRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACTORYREADREQUEST,
  '__module__' : 'factory_command_pb2'
  # @@protoc_insertion_point(class_scope:factory.command.FactoryReadRequest)
  })
_sym_db.RegisterMessage(FactoryReadRequest)

FactoryReadResponse = _reflection.GeneratedProtocolMessageType('FactoryReadResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACTORYREADRESPONSE,
  '__module__' : 'factory_command_pb2'
  # @@protoc_insertion_point(class_scope:factory.command.FactoryReadResponse)
  })
_sym_db.RegisterMessage(FactoryReadResponse)

FactoryWriteRequest = _reflection.GeneratedProtocolMessageType('FactoryWriteRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACTORYWRITEREQUEST,
  '__module__' : 'factory_command_pb2'
  # @@protoc_insertion_point(class_scope:factory.command.FactoryWriteRequest)
  })
_sym_db.RegisterMessage(FactoryWriteRequest)

FactoryWriteResponse = _reflection.GeneratedProtocolMessageType('FactoryWriteResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACTORYWRITERESPONSE,
  '__module__' : 'factory_command_pb2'
  # @@protoc_insertion_point(class_scope:factory.command.FactoryWriteResponse)
  })
_sym_db.RegisterMessage(FactoryWriteResponse)


# @@protoc_insertion_point(module_scope)
