# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: factory_command.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'factory_command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import factory_data_pb2 as factory__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66\x61\x63tory_command.proto\x12\x0f\x66\x61\x63tory.command\x1a\x12\x66\x61\x63tory_data.proto\"B\n\x12\x46\x61\x63toryReadRequest\x12,\n\x05items\x18\x01 \x03(\x0e\x32\x1d.factory.data.FactoryDataItem\">\n\x13\x46\x61\x63toryReadResponse\x12\'\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x19.factory.data.FactoryData\">\n\x13\x46\x61\x63toryWriteRequest\x12\'\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x19.factory.data.FactoryData\"D\n\x14\x46\x61\x63toryWriteResponse\x12,\n\x05items\x18\x01 \x03(\x0e\x32\x1d.factory.data.FactoryDataItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'factory_command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACTORYREADREQUEST']._serialized_start=62
  _globals['_FACTORYREADREQUEST']._serialized_end=128
  _globals['_FACTORYREADRESPONSE']._serialized_start=130
  _globals['_FACTORYREADRESPONSE']._serialized_end=192
  _globals['_FACTORYWRITEREQUEST']._serialized_start=194
  _globals['_FACTORYWRITEREQUEST']._serialized_end=256
  _globals['_FACTORYWRITERESPONSE']._serialized_start=258
  _globals['_FACTORYWRITERESPONSE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
